import { defineConfig } from "eslint/config";

import { baseConfig } from "@acme/eslint-config/base";

export default defineConfig(
  {
    // payload-types.ts is generated by `pnpm cms:gen-types` — never hand-edit/lint it.
    ignores: ["dist/**", "src/payload-types.ts"],
  },
  baseConfig,
);
