-- Seed data for local dev. Runs after migrations on `supabase db reset`.
--
-- This kit ships with NO seeded users or demo rows: the database starts empty so
-- that the FIRST user who signs up through the app UI becomes the owner. The
-- handle_new_user() trigger flags the first profile as staff (is_staff = true),
-- which grants Payload CMS admin access via the Supabase->Payload SSO bridge.
-- See supabase/migrations/20260601010008_cms_staff.sql.
--
-- To exercise the app, run it (`pnpm dev`), open the web app, and sign up — that
-- account is the founder/admin. Public content (articles, events, pages) lives in
-- Payload and is seeded separately with `pnpm cms:seed` (or automatically the
-- first time a staff user opens /admin).
--
-- Add your own demo rows below if you want sample data for local development.
-- Cross-user RLS isolation is exercised by tooling/rls-tests, which provisions
-- its own throwaway users via the Supabase admin API (it does not rely on seed
-- data), so an empty seed keeps that suite green.
