/* eslint-disable */
// GENERATED by `pnpm ext sync` — DO NOT EDIT.
// Recomputed from extensions/*/extension.config.ts; a stale copy fails
// `pnpm test` via apps/nextjs/src/ext/registry-drift.test.ts.
import type { ReactNode } from "react";
import { notFound } from "next/navigation";

import { isExtensionEnabled } from "~/lib/ext/enabled";

/** Runtime enable/disable gate — disabling the extension 404s its pages. */
export default async function ExtensionLayout({
  children,
}: {
  children: ReactNode;
}) {
  if (!(await isExtensionEnabled("chat"))) notFound();
  return children;
}
