/* eslint-disable */
// GENERATED by `pnpm ext sync` — DO NOT EDIT.
// Recomputed from extensions/*/extension.config.ts; a stale copy fails
// `pnpm test` via apps/nextjs/src/ext/registry-drift.test.ts.
/** Extension client env (EXPO_PUBLIC_EXT_*) — none installed declare any. */
export const extEnv = {};
