/* eslint-disable */
// GENERATED by `pnpm ext sync` — DO NOT EDIT.
// Recomputed from extensions/*/extension.config.ts; a stale copy fails
// `pnpm test` via apps/nextjs/src/ext/registry-drift.test.ts.
import type * as React from "react";

export interface ExtInstalled {
  slug: string;
  name: string;
  version: string;
  /** True when the app shell depends on this extension's mounts (e.g. the home screen). */
  system: boolean;
}

export interface ExtNavDefault {
  key: string;
  extension: string;
  title: string;
  href: string;
  icon?: string;
  order: number;
}

export const extInstalled: ExtInstalled[] = [];

/** Native nav defaults — fallback for useNavMenu() while offline/loading. */
export const extNavDefaults: { native: ExtNavDefault[] } = {
  native: [],
};

/** Home-screen widgets declared by installed extensions (native components). */
export const extWidgets: { slug: string; Widget: React.ComponentType }[] = [];

export function hasExtension(slug: string): boolean {
  return extInstalled.some((e) => e.slug === slug);
}
