/* eslint-disable */
// GENERATED by `pnpm ext sync` — DO NOT EDIT.
// Recomputed from extensions/*/extension.config.ts; a stale copy fails
// `pnpm test` via apps/nextjs/src/ext/registry-drift.test.ts.
import type * as React from "react";
import "@acme/ext-chat/native";
import "@acme/ext-notifications/native";
import "@acme/ext-reminders/native";

export interface ExtInstalled {
  slug: string;
  name: string;
  version: string;
  /** True when the app shell depends on this extension's mounts (e.g. the home screen). */
  system: boolean;
}

export interface ExtNavDefault {
  key: string;
  extension: string;
  title: string;
  href: string;
  icon?: string;
  order: number;
}

export const extInstalled: ExtInstalled[] = [
  { slug: "billing", name: "Billing", version: "1.0.0", system: false },
  { slug: "chat", name: "AI Chat", version: "1.0.0", system: false },
  { slug: "notifications", name: "Notifications", version: "1.0.0", system: false },
  { slug: "reminders", name: "Reminders", version: "1.0.0", system: false },
];

/** Native nav defaults — fallback for useNavMenu() while offline/loading. */
export const extNavDefaults: { native: ExtNavDefault[] } = {
  native: [
    { key: "ext:chat:0", extension: "chat", title: "Chat", href: "/x/chat", icon: "IconMessageCircle", order: 20 },
    { key: "ext:notifications:0", extension: "notifications", title: "Notifications", href: "/x/notifications", icon: "IconBell", order: 40 },
    { key: "ext:reminders:0", extension: "reminders", title: "Reminders", href: "/x/reminders", icon: "IconClock", order: 30 },
  ],
};

/** Home-screen widgets declared by installed extensions (native components). */
export const extWidgets: { slug: string; Widget: React.ComponentType }[] = [];

export function hasExtension(slug: string): boolean {
  return extInstalled.some((e) => e.slug === slug);
}
