import { defineConfig } from "eslint/config";

import { baseConfig, restrictEnvAccess } from "@acme/eslint-config/base";
import { nextjsConfig } from "@acme/eslint-config/nextjs";
import { reactConfig } from "@acme/eslint-config/react";

export default defineConfig(
  {
    // `.next/**` is build output; `src/app/(payload)/**` is Payload-generated
    // mount boilerplate ("DO NOT MODIFY") that uses framework patterns our lint
    // rules would otherwise reject; `src/payload/migrations/**` is generated by
    // `pnpm cms:migrate:create` (never hand-edited) and ships verbatim; the
    // ext registries + route stubs are regenerated wholesale by `pnpm ext sync`.
    ignores: [
      ".next/**",
      "src/app/(payload)/**",
      "src/payload/migrations/**",
      "src/ext/*.generated.ts",
      "src/app/(frontend)/(app)/x/**",
      "src/app/(frontend)/(public)/x/**",
    ],
  },
  baseConfig,
  reactConfig,
  nextjsConfig,
  restrictEnvAccess,
  {
    // Bundle safety (EXTENSIONS-PLAN.md §1.3): extension `./native` entries
    // are react-native code and must never enter the web bundle. (The reverse
    // poison pills — `server-only` + the payload import — guard /server and
    // /payload at compile time.)
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@acme/ext-*/native"],
              message:
                "Extension /native entries are react-native-only — import the client barrel or /web here.",
            },
          ],
        },
      ],
    },
  },
  {
    // Vendored shadcn/ui block components (added via `npx shadcn add`) are
    // copy-own source we don't hold to the same strict type-checked lint rules.
    // Our own app code under src/app/** stays fully strict.
    files: ["src/components/**"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/consistent-type-imports": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "import/consistent-type-specifier-style": "off",
      "react-hooks/incompatible-library": "off",
      "react-hooks/purity": "off",
    },
  },
);
