import { readFileSync } from "node:fs";
import { withPayload } from "@payloadcms/next/withPayload";
import { createJiti } from "jiti";

const jiti = createJiti(import.meta.url);

// Import env files to validate at build time. Use jiti so we can load .ts files in here.
await jiti.import("./src/env");

// Installed extension packages (generated by `pnpm ext sync`) — they're
// source-only workspace packages like @acme/app, so Next must transpile them.
const extPackages = /** @type {string[]} */ (
  JSON.parse(
    readFileSync(
      new URL("./ext-packages.generated.json", import.meta.url),
      "utf8",
    ),
  )
);

/** @type {import("next").NextConfig} */
const config = {
  /** Enables hot reloading for local packages without a build step */
  transpilePackages: [
    "@acme/api",
    "@acme/app",
    "@acme/cms",
    "@acme/config",
    "@acme/ext-kit",
    "@acme/ui",
    ...extPackages,
  ],

  /** We already do linting and typechecking as separate tasks in CI */
  typescript: { ignoreBuildErrors: true },

  /**
   * Legacy paths from before the extension refactor — features extracted into
   * extensions now mount under /x/<slug> (EXTENSIONS-PLAN.md §2); old links
   * and bookmarks keep working.
   */
  redirects: () =>
    Promise.resolve([
      {
        source: "/notifications",
        destination: "/x/notifications",
        permanent: true,
      },
      {
        source: "/reminders",
        destination: "/x/reminders",
        permanent: true,
      },
      { source: "/chat", destination: "/x/chat", permanent: true },
      {
        source: "/chat/:id",
        destination: "/x/chat/:id",
        permanent: true,
      },
    ]),

  /**
   * `pg` (the runtime DB bootstrap's driver, lib/db/bootstrap.ts) must stay a
   * Node require — bundling trips on its optional native `pg-native` import.
   */
  serverExternalPackages: ["pg"],
};

// `withPayload` mounts the Payload admin (/admin) + REST API. Payload's admin has
// historically expected the webpack build path — if the admin fails to compile under
// Next's default bundler, run the web app with `next dev --webpack` / `next build --webpack`.
export default withPayload(config);
