/* eslint-disable */
// GENERATED by `pnpm ext sync` — DO NOT EDIT.
// Recomputed from extensions/*/extension.config.ts; a stale copy fails
// `pnpm test` via apps/nextjs/src/ext/registry-drift.test.ts.
/** Merged server-only env shapes from installed extensions (EXT_*). */
export const extServerEnv = {};

/** Merged client env shapes (NEXT_PUBLIC_EXT_*). */
export const extClientEnv = {};

/** Literal process.env reads (t3-env requires them for client vars). */
export const extClientRuntimeEnv = {};
