/* eslint-disable */
// GENERATED by `pnpm ext sync` — DO NOT EDIT.
// Recomputed from extensions/*/extension.config.ts; a stale copy fails
// `pnpm test` via apps/nextjs/src/ext/registry-drift.test.ts.
import type * as React from "react";
import { IconBell, IconClock, IconCreditCard, IconDashboard, IconMessageCircle } from "@tabler/icons-react";
import { BillingWidget as widget_billing } from "@acme/ext-billing/web";
import { ChatWidget as widget_chat } from "@acme/ext-chat/web";
import { NotificationsWidget as widget_notifications } from "@acme/ext-notifications/web";
import { RemindersWidget as widget_reminders } from "@acme/ext-reminders/web";

export interface ExtInstalled {
  slug: string;
  name: string;
  version: string;
  /** True when the app shell depends on this extension's mounts (e.g. the home screen). */
  system: boolean;
}

export interface ExtNavDefault {
  key: string;
  extension: string;
  title: string;
  href: string;
  icon?: string;
  order: number;
}

/** Every installed extension (from the vendored manifests). */
export const extInstalled: ExtInstalled[] = [
  { slug: "billing", name: "Billing", version: "1.0.0", system: true },
  { slug: "chat", name: "AI Chat", version: "1.0.0", system: false },
  { slug: "chat-adapter-sendblue", name: "Sendblue Adapter", version: "1.0.0", system: false },
  { slug: "chat-adapter-slack", name: "Slack Adapter", version: "1.0.0", system: false },
  { slug: "dashboard", name: "Dashboard", version: "1.0.0", system: true },
  { slug: "docs", name: "Docs", version: "1.0.0", system: true },
  { slug: "notifications", name: "Notifications", version: "1.0.0", system: false },
  { slug: "reminders", name: "Reminders", version: "1.0.0", system: false },
];

/**
 * Manifest nav DEFAULTS — seeded into the CMS-driven menu by the boot
 * reconcile (lib/ext/reconcile-nav.ts), never rendered directly.
 */
export const extNavDefaults: { web: ExtNavDefault[]; native: ExtNavDefault[] } = {
  web: [
    { key: "ext:billing:0", extension: "billing", title: "Billing", href: "/billing", icon: "IconCreditCard", order: 50 },
    { key: "ext:chat:0", extension: "chat", title: "Chat", href: "/a/chat", icon: "IconMessageCircle", order: 20 },
    { key: "ext:dashboard:0", extension: "dashboard", title: "Dashboard", href: "/a", icon: "IconDashboard", order: 10 },
    { key: "ext:notifications:0", extension: "notifications", title: "Notifications", href: "/a/notifications", icon: "IconBell", order: 40 },
    { key: "ext:reminders:0", extension: "reminders", title: "Reminders", href: "/a/reminders", icon: "IconClock", order: 30 },
  ],
  native: [
    { key: "ext:billing:0", extension: "billing", title: "Pricing", href: "/a/billing", order: 55 },
    { key: "ext:chat:0", extension: "chat", title: "Chat", href: "/a/chat", icon: "IconMessageCircle", order: 20 },
    { key: "ext:notifications:0", extension: "notifications", title: "Notifications", href: "/a/notifications", icon: "IconBell", order: 40 },
    { key: "ext:reminders:0", extension: "reminders", title: "Reminders", href: "/a/reminders", icon: "IconClock", order: 30 },
  ],
};

/** Dashboard widgets declared by installed extensions (web components). */
export const extWidgets: { slug: string; Widget: React.ComponentType }[] = [
  { slug: "billing", Widget: widget_billing },
  { slug: "chat", Widget: widget_chat },
  { slug: "notifications", Widget: widget_notifications },
  { slug: "reminders", Widget: widget_reminders },
];

/** Icon names referenced by extension nav defaults → components. */
export const extIcons: Record<string, React.ComponentType<{ className?: string }>> = {
  IconBell: IconBell,
  IconClock: IconClock,
  IconCreditCard: IconCreditCard,
  IconDashboard: IconDashboard,
  IconMessageCircle: IconMessageCircle,
};

export function hasExtension(slug: string): boolean {
  return extInstalled.some((e) => e.slug === slug);
}
