/* eslint-disable */
// GENERATED by `pnpm ext sync` — DO NOT EDIT.
// Recomputed from extensions/*/extension.config.ts; a stale copy fails
// `pnpm test` via apps/nextjs/src/ext/registry-drift.test.ts.
import "server-only";

import type { ExtRouteTable } from "@acme/ext-kit/server";

/** slug → route table, dispatched by /api/ext/[ext]/[[...route]]. */
export const extServerRoutes: Record<string, ExtRouteTable> = {};
