/* eslint-disable */
// GENERATED by `pnpm ext sync` — DO NOT EDIT.
// Recomputed from extensions/*/extension.config.ts; a stale copy fails
// `pnpm test` via apps/nextjs/src/ext/registry-drift.test.ts.
import type { CollectionConfig, Config, GlobalConfig } from "payload";

import type { ExtensionSettings, ExtSeedStep } from "@acme/ext-kit/payload";
import { composeSettingsTabs } from "@acme/ext-kit/payload";

import * as payload_billing from "@acme/ext-billing/payload";
import * as payload_chat from "@acme/ext-chat/payload";
import * as payload_chat_adapter_sendblue from "@acme/ext-chat-adapter-sendblue/payload";
import * as payload_chat_adapter_slack from "@acme/ext-chat-adapter-slack/payload";
import * as payload_docs from "@acme/ext-docs/payload";

export interface ExtPayloadMigration {
  name: string;
  up: (args: any) => Promise<void>;
  down: (args: any) => Promise<void>;
}

const chatSettings = composeSettingsTabs(payload_chat.settings, [
  payload_chat_adapter_sendblue.settings,
  payload_chat_adapter_slack.settings,
]);

export const extCollections: CollectionConfig[] = [
  ...payload_billing.collections,
  ...payload_chat.collections,
  ...payload_docs.collections,
];

export const extGlobals: GlobalConfig[] = [
  payload_billing.settings.global,
  chatSettings.global,
  payload_docs.settings.global,
];

export const extPlugins: NonNullable<Config["plugins"]> = [
  ...payload_billing.plugins,
];

export const extPayloadMigrations: ExtPayloadMigration[] = [
  ...payload_billing.migrations,
  ...payload_chat.migrations,
  ...payload_chat_adapter_sendblue.migrations,
  ...payload_chat_adapter_slack.migrations,
  ...payload_docs.migrations,
];

export const extSeedSteps: ExtSeedStep[] = [
  ...payload_billing.seed,
  ...payload_chat.seed,
  ...payload_docs.seed,
];

/** slug → settings definition (admin settings screens, §1.7). */
export const extSettings: Record<string, ExtensionSettings> = {
  "billing": payload_billing.settings,
  "chat": chatSettings,
  "docs": payload_docs.settings,
};
