import { defineConfig } from "eslint/config";

import { baseConfig } from "@acme/eslint-config/base";
import { reactConfig } from "@acme/eslint-config/react";

export default defineConfig(
  {
    // payload/migrations/** is generated by `payload migrate:create`
    // (relocated here by the payload-migrate flow) and ships verbatim.
    ignores: ["supabase/**", "src/payload/migrations/2*"],
  },
  baseConfig,
  reactConfig,
  {
    // Client islands drive the DOM (scroll-spy TOC, selection toolbar) and
    // fetch-then-setState in effects — both legitimate here. Relax the two
    // rules that flag those patterns; the rest of the strict config stands.
    files: ["src/web/**"],
    rules: {
      "@typescript-eslint/no-unnecessary-condition": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
);
