/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    events: Event;
    videos: Video;
    audio: Audio;
    photos: Photo;
    locations: Location;
    pages: Page;
    plans: Plan;
    coupons: Coupon;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    audio: AudioSelect<false> | AudioSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'theme-settings': ThemeSetting;
    'pricing-settings': PricingSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
    'pricing-settings': PricingSettingsSelect<false> | PricingSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * All app users — members and staff. Creating a NEW email emails a Supabase invite and grants staff access; for an existing user use “Grant staff access”. User tags (incl. the plan-name tag) are managed below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  email?: string | null;
  name?: string | null;
  /**
   * Public display name. Falls back to the account name.
   */
  displayName?: string | null;
  /**
   * Linked Supabase auth user id (managed by the SSO bridge).
   */
  supabaseUserId?: string | null;
  /**
   * admin/editor/author may enter /admin (with staff access granted); member is an app user.
   */
  roles: ('admin' | 'editor' | 'author' | 'member')[];
  memberStatus?: ('active' | 'invited' | 'suspended' | 'banned') | null;
  /**
   * Public handle / profile URL slug.
   */
  username?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  pronouns?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Profile banner image.
   */
  coverImage?: (number | null) | Media;
  /**
   * Short tagline shown on the profile.
   */
  headline?: string | null;
  /**
   * About — shown for author-role users.
   */
  bio?: string | null;
  location?: string | null;
  website?: string | null;
  company?: string | null;
  jobTitle?: string | null;
  socialLinks?: {
    twitter?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    facebook?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    github?: string | null;
  };
  profileVisibility?: ('public' | 'members' | 'private') | null;
  /**
   * How they found the app (optional).
   */
  referralSource?: string | null;
  /**
   * Required before any SMS send.
   */
  phone?: string | null;
  dateOfBirth?: string | null;
  /**
   * IANA timezone — used for scheduling and digests.
   */
  timezone?:
    | (
        | 'Pacific/Midway'
        | 'Pacific/Niue'
        | 'Pacific/Honolulu'
        | 'Pacific/Rarotonga'
        | 'America/Anchorage'
        | 'Pacific/Gambier'
        | 'America/Los_Angeles'
        | 'America/Tijuana'
        | 'America/Denver'
        | 'America/Phoenix'
        | 'America/Chicago'
        | 'America/Guatemala'
        | 'America/New_York'
        | 'America/Bogota'
        | 'America/Caracas'
        | 'America/Santiago'
        | 'America/Buenos_Aires'
        | 'America/Sao_Paulo'
        | 'Atlantic/South_Georgia'
        | 'Atlantic/Azores'
        | 'Atlantic/Cape_Verde'
        | 'Europe/London'
        | 'Europe/Berlin'
        | 'Africa/Lagos'
        | 'Europe/Athens'
        | 'Africa/Cairo'
        | 'Europe/Moscow'
        | 'Asia/Riyadh'
        | 'Asia/Dubai'
        | 'Asia/Baku'
        | 'Asia/Karachi'
        | 'Asia/Tashkent'
        | 'Asia/Calcutta'
        | 'Asia/Dhaka'
        | 'Asia/Almaty'
        | 'Asia/Jakarta'
        | 'Asia/Bangkok'
        | 'Asia/Shanghai'
        | 'Asia/Singapore'
        | 'Asia/Tokyo'
        | 'Asia/Seoul'
        | 'Australia/Brisbane'
        | 'Australia/Sydney'
        | 'Pacific/Guam'
        | 'Pacific/Noumea'
        | 'Pacific/Auckland'
        | 'Pacific/Fiji'
      )
    | null;
  preferredLanguage?: ('en' | 'es' | 'fr' | 'de' | 'pt' | 'it' | 'ja' | 'ko' | 'zh') | null;
  /**
   * Optional billing address.
   */
  address?: {
    street?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  pushEnabled?: boolean | null;
  /**
   * Explicit SMS consent — required before any SMS send; phone must be present.
   */
  smsOptIn?: boolean | null;
  marketingOptIn?: boolean | null;
  notificationPreferences?: {
    emailDigest?: ('off' | 'daily' | 'weekly') | null;
    communityReplies?: boolean | null;
    mentions?: boolean | null;
    directMessages?: boolean | null;
    productUpdates?: boolean | null;
  };
  onboardingCompleted?: boolean | null;
  /**
   * Updated on app launch.
   */
  lastActiveAt?: string | null;
  stripeCustomerID?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  tags?: string[] | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startsAt: string;
  endsAt?: string | null;
  location?: (number | null) | Location;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  slug: string;
  address?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  sourceType: 'url' | 'upload';
  url?: string | null;
  file?: (number | null) | Media;
  thumbnail?: (number | null) | Media;
  /**
   * Length in seconds.
   */
  duration?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio".
 */
export interface Audio {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  audioFile: number | Media;
  /**
   * Length in seconds.
   */
  duration?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  title: string;
  slug: string;
  image: number | Media;
  caption?: string | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?: (HeroBlock | ItemsBlock | LogosBlock | StatsBlock | CTABlock | FAQBlock | ProseBlock)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  title: string;
  description?: string | null;
  /**
   * Small pill above the title.
   */
  badgeText?: string | null;
  badgeLinkText?: string | null;
  badgeLinkHref?: string | null;
  buttons?:
    | {
        text: string;
        href: string;
        variant?: ('default' | 'glow' | 'outline' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Hero screenshot (light mode).
   */
  mockupLight?: (number | null) | Media;
  /**
   * Optional dark-mode variant of the screenshot.
   */
  mockupDark?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ItemsBlock".
 */
export interface ItemsBlock {
  title?: string | null;
  items?:
    | {
        title: string;
        description: string;
        /**
         * Optional lucide icon.
         */
        icon?:
          | (
              | 'Rocket'
              | 'Zap'
              | 'ShieldCheck'
              | 'Sparkles'
              | 'Star'
              | 'Heart'
              | 'Globe'
              | 'Code'
              | 'Layers'
              | 'Smartphone'
              | 'Palette'
              | 'Lock'
              | 'Check'
              | 'Cloud'
              | 'Bell'
              | 'Settings'
              | 'Users'
              | 'ChartBar'
              | 'Search'
              | 'Mail'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'items';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock".
 */
export interface LogosBlock {
  title?: string | null;
  badgeText?: string | null;
  logos?:
    | {
        name: string;
        /**
         * Optional logo image; falls back to the name.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  items?:
    | {
        label?: string | null;
        value: string;
        suffix?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  title: string;
  buttons?:
    | {
        text: string;
        href: string;
        variant?: ('default' | 'glow' | 'outline' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  title?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock".
 */
export interface ProseBlock {
  title?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'prose';
}
/**
 * Author plans here, then press “Sync to Stripe” to create/update the matching Stripe product and price. Stripe prices are immutable, so changing the amount creates a new price and archives the old one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name: string;
  active?: boolean | null;
  slug: string;
  description?: string | null;
  pricingType: 'recurring' | 'one_time';
  interval?: ('month' | 'year') | null;
  /**
   * Amount in the smallest currency unit, e.g. 999 = $9.99.
   */
  unitAmount: number;
  /**
   * ISO code, e.g. usd.
   */
  currency: string;
  /**
   * 0 / empty = no trial.
   */
  trialDays?: number | null;
  /**
   * Discount the first billing period only (e.g. $1.99 first month, then the standard price recurs). Implemented as a Stripe coupon with duration=once, applied automatically at checkout.
   */
  introOffer?: {
    enabled?: boolean | null;
    /**
     * First-period price, e.g. 199 = $1.99.
     */
    introAmount?: number | null;
  };
  /**
   * Shown on the public pricing card.
   */
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "Save 17%" or "Best value".
   */
  badge?: string | null;
  highlighted?: boolean | null;
  displayOrder?: number | null;
  stripeProductId?: string | null;
  stripePriceId?: string | null;
  stripeIntroCouponId?: string | null;
  syncStatus?: ('unsynced' | 'synced' | 'error') | null;
  syncError?: string | null;
  lastSyncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Discounts pushed to Stripe. Changing amount/duration creates a new Stripe coupon (they're immutable) and archives the old one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  name: string;
  discountType: 'percent_off' | 'amount_off';
  /**
   * Percent (1–100) or amount in cents.
   */
  value: number;
  currency?: string | null;
  duration: 'once' | 'repeating' | 'forever';
  durationCount?: number | null;
  /**
   * Years are converted to months for Stripe (2 years → 24 months).
   */
  durationUnit?: ('month' | 'year') | null;
  /**
   * Total redemptions allowed.
   */
  maxRedemptions?: number | null;
  /**
   * Stripe redeem_by — no new redemptions after this.
   */
  redeemBy?: string | null;
  /**
   * Restrict to specific plans (empty = applies to all).
   */
  appliesTo?: (number | Plan)[] | null;
  /**
   * Optional customer-facing code (e.g. LAUNCH20). Created as a Stripe promotion code on sync. Leave blank for a code-less coupon.
   */
  code?: string | null;
  /**
   * When set, new free signups get a unique, expiring promotion code for this coupon. Keep at most one active.
   */
  isWelcomeOffer?: boolean | null;
  stripeCouponId?: string | null;
  stripePromotionCodeId?: string | null;
  syncStatus?: ('unsynced' | 'synced' | 'error') | null;
  syncError?: string | null;
  lastSyncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'audio';
        value: number | Audio;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  displayName?: T;
  supabaseUserId?: T;
  roles?: T;
  memberStatus?: T;
  username?: T;
  firstName?: T;
  lastName?: T;
  pronouns?: T;
  avatar?: T;
  coverImage?: T;
  headline?: T;
  bio?: T;
  location?: T;
  website?: T;
  company?: T;
  jobTitle?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        instagram?: T;
        linkedin?: T;
        facebook?: T;
        youtube?: T;
        tiktok?: T;
        github?: T;
      };
  profileVisibility?: T;
  referralSource?: T;
  phone?: T;
  dateOfBirth?: T;
  timezone?: T;
  preferredLanguage?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  pushEnabled?: T;
  smsOptIn?: T;
  marketingOptIn?: T;
  notificationPreferences?:
    | T
    | {
        emailDigest?: T;
        communityReplies?: T;
        mentions?: T;
        directMessages?: T;
        productUpdates?: T;
      };
  onboardingCompleted?: T;
  lastActiveAt?: T;
  stripeCustomerID?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  author?: T;
  tags?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  sourceType?: T;
  url?: T;
  file?: T;
  thumbnail?: T;
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio_select".
 */
export interface AudioSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  audioFile?: T;
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  caption?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        items?: T | ItemsBlockSelect<T>;
        logos?: T | LogosBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        prose?: T | ProseBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  badgeText?: T;
  badgeLinkText?: T;
  badgeLinkHref?: T;
  buttons?:
    | T
    | {
        text?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  mockupLight?: T;
  mockupDark?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ItemsBlock_select".
 */
export interface ItemsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock_select".
 */
export interface LogosBlockSelect<T extends boolean = true> {
  title?: T;
  badgeText?: T;
  logos?:
    | T
    | {
        name?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        value?: T;
        suffix?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  title?: T;
  buttons?:
    | T
    | {
        text?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock_select".
 */
export interface ProseBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  active?: T;
  slug?: T;
  description?: T;
  pricingType?: T;
  interval?: T;
  unitAmount?: T;
  currency?: T;
  trialDays?: T;
  introOffer?:
    | T
    | {
        enabled?: T;
        introAmount?: T;
      };
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  badge?: T;
  highlighted?: T;
  displayOrder?: T;
  stripeProductId?: T;
  stripePriceId?: T;
  stripeIntroCouponId?: T;
  syncStatus?: T;
  syncError?: T;
  lastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  name?: T;
  discountType?: T;
  value?: T;
  currency?: T;
  duration?: T;
  durationCount?: T;
  durationUnit?: T;
  maxRedemptions?: T;
  redeemBy?: T;
  appliesTo?: T;
  code?: T;
  isWelcomeOffer?: T;
  stripeCouponId?: T;
  stripePromotionCodeId?: T;
  syncStatus?: T;
  syncError?: T;
  lastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Top-level nav items. Add sub-items to render a dropdown menu.
   */
  header?:
    | {
        label: string;
        url: string;
        submenu?:
          | {
              label: string;
              url: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Right-aligned links/buttons, e.g. Sign in and Get started.
   */
  headerActions?:
    | {
        label: string;
        url: string;
        variant?: ('default' | 'glow' | 'outline' | 'secondary') | null;
        isButton?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerPolicies?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Bottom-bar copyright. Defaults to © {year} {app name}.
   */
  copyright?: string | null;
  social?: {
    twitter?: string | null;
    github?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Branding, colors, typography and styles for the entire app and this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  /**
   * Display name shown in the app shell and tab title.
   */
  appName?: string | null;
  /**
   * Where the header logo/wordmark links to.
   */
  brandLink?: {
    /**
     * Internal path (e.g. /pricing) or full external URL (https://example.com).
     */
    url?: string | null;
    newTab?: boolean | null;
  };
  /**
   * Square icon — used as the favicon (512×512 ideal).
   */
  appIcon?: (number | null) | Media;
  /**
   * Logo shown on light backgrounds.
   */
  logoLight?: (number | null) | Media;
  /**
   * Logo shown on dark backgrounds.
   */
  logoDark?: (number | null) | Media;
  colorsLight?: {
    /**
     * --background · any CSS color (oklch recommended)
     */
    background?: string | null;
    /**
     * --foreground · any CSS color (oklch recommended)
     */
    foreground?: string | null;
    /**
     * --card · any CSS color (oklch recommended)
     */
    card?: string | null;
    /**
     * --card-foreground · any CSS color (oklch recommended)
     */
    cardForeground?: string | null;
    /**
     * --popover · any CSS color (oklch recommended)
     */
    popover?: string | null;
    /**
     * --popover-foreground · any CSS color (oklch recommended)
     */
    popoverForeground?: string | null;
    /**
     * --primary · any CSS color (oklch recommended)
     */
    primary?: string | null;
    /**
     * --primary-foreground · any CSS color (oklch recommended)
     */
    primaryForeground?: string | null;
    /**
     * --secondary · any CSS color (oklch recommended)
     */
    secondary?: string | null;
    /**
     * --secondary-foreground · any CSS color (oklch recommended)
     */
    secondaryForeground?: string | null;
    /**
     * --muted · any CSS color (oklch recommended)
     */
    muted?: string | null;
    /**
     * --muted-foreground · any CSS color (oklch recommended)
     */
    mutedForeground?: string | null;
    /**
     * --accent · any CSS color (oklch recommended)
     */
    accent?: string | null;
    /**
     * --accent-foreground · any CSS color (oklch recommended)
     */
    accentForeground?: string | null;
    /**
     * --destructive · any CSS color (oklch recommended)
     */
    destructive?: string | null;
    /**
     * --destructive-foreground · any CSS color (oklch recommended)
     */
    destructiveForeground?: string | null;
    /**
     * --border · any CSS color (oklch recommended)
     */
    border?: string | null;
    /**
     * --input · any CSS color (oklch recommended)
     */
    input?: string | null;
    /**
     * --ring · any CSS color (oklch recommended)
     */
    ring?: string | null;
    /**
     * --chart-1 · any CSS color (oklch recommended)
     */
    chart1?: string | null;
    /**
     * --chart-2 · any CSS color (oklch recommended)
     */
    chart2?: string | null;
    /**
     * --chart-3 · any CSS color (oklch recommended)
     */
    chart3?: string | null;
    /**
     * --chart-4 · any CSS color (oklch recommended)
     */
    chart4?: string | null;
    /**
     * --chart-5 · any CSS color (oklch recommended)
     */
    chart5?: string | null;
    /**
     * --sidebar · any CSS color (oklch recommended)
     */
    sidebar?: string | null;
    /**
     * --sidebar-foreground · any CSS color (oklch recommended)
     */
    sidebarForeground?: string | null;
    /**
     * --sidebar-primary · any CSS color (oklch recommended)
     */
    sidebarPrimary?: string | null;
    /**
     * --sidebar-primary-foreground · any CSS color (oklch recommended)
     */
    sidebarPrimaryForeground?: string | null;
    /**
     * --sidebar-accent · any CSS color (oklch recommended)
     */
    sidebarAccent?: string | null;
    /**
     * --sidebar-accent-foreground · any CSS color (oklch recommended)
     */
    sidebarAccentForeground?: string | null;
    /**
     * --sidebar-border · any CSS color (oklch recommended)
     */
    sidebarBorder?: string | null;
    /**
     * --sidebar-ring · any CSS color (oklch recommended)
     */
    sidebarRing?: string | null;
    /**
     * --brand · any CSS color (oklch recommended)
     */
    brand?: string | null;
    /**
     * --brand-foreground · any CSS color (oklch recommended)
     */
    brandForeground?: string | null;
  };
  colorsDark?: {
    /**
     * --background · any CSS color (oklch recommended)
     */
    background?: string | null;
    /**
     * --foreground · any CSS color (oklch recommended)
     */
    foreground?: string | null;
    /**
     * --card · any CSS color (oklch recommended)
     */
    card?: string | null;
    /**
     * --card-foreground · any CSS color (oklch recommended)
     */
    cardForeground?: string | null;
    /**
     * --popover · any CSS color (oklch recommended)
     */
    popover?: string | null;
    /**
     * --popover-foreground · any CSS color (oklch recommended)
     */
    popoverForeground?: string | null;
    /**
     * --primary · any CSS color (oklch recommended)
     */
    primary?: string | null;
    /**
     * --primary-foreground · any CSS color (oklch recommended)
     */
    primaryForeground?: string | null;
    /**
     * --secondary · any CSS color (oklch recommended)
     */
    secondary?: string | null;
    /**
     * --secondary-foreground · any CSS color (oklch recommended)
     */
    secondaryForeground?: string | null;
    /**
     * --muted · any CSS color (oklch recommended)
     */
    muted?: string | null;
    /**
     * --muted-foreground · any CSS color (oklch recommended)
     */
    mutedForeground?: string | null;
    /**
     * --accent · any CSS color (oklch recommended)
     */
    accent?: string | null;
    /**
     * --accent-foreground · any CSS color (oklch recommended)
     */
    accentForeground?: string | null;
    /**
     * --destructive · any CSS color (oklch recommended)
     */
    destructive?: string | null;
    /**
     * --destructive-foreground · any CSS color (oklch recommended)
     */
    destructiveForeground?: string | null;
    /**
     * --border · any CSS color (oklch recommended)
     */
    border?: string | null;
    /**
     * --input · any CSS color (oklch recommended)
     */
    input?: string | null;
    /**
     * --ring · any CSS color (oklch recommended)
     */
    ring?: string | null;
    /**
     * --chart-1 · any CSS color (oklch recommended)
     */
    chart1?: string | null;
    /**
     * --chart-2 · any CSS color (oklch recommended)
     */
    chart2?: string | null;
    /**
     * --chart-3 · any CSS color (oklch recommended)
     */
    chart3?: string | null;
    /**
     * --chart-4 · any CSS color (oklch recommended)
     */
    chart4?: string | null;
    /**
     * --chart-5 · any CSS color (oklch recommended)
     */
    chart5?: string | null;
    /**
     * --sidebar · any CSS color (oklch recommended)
     */
    sidebar?: string | null;
    /**
     * --sidebar-foreground · any CSS color (oklch recommended)
     */
    sidebarForeground?: string | null;
    /**
     * --sidebar-primary · any CSS color (oklch recommended)
     */
    sidebarPrimary?: string | null;
    /**
     * --sidebar-primary-foreground · any CSS color (oklch recommended)
     */
    sidebarPrimaryForeground?: string | null;
    /**
     * --sidebar-accent · any CSS color (oklch recommended)
     */
    sidebarAccent?: string | null;
    /**
     * --sidebar-accent-foreground · any CSS color (oklch recommended)
     */
    sidebarAccentForeground?: string | null;
    /**
     * --sidebar-border · any CSS color (oklch recommended)
     */
    sidebarBorder?: string | null;
    /**
     * --sidebar-ring · any CSS color (oklch recommended)
     */
    sidebarRing?: string | null;
    /**
     * --brand · any CSS color (oklch recommended)
     */
    brand?: string | null;
    /**
     * --brand-foreground · any CSS color (oklch recommended)
     */
    brandForeground?: string | null;
  };
  /**
   * Body / UI font (--font-sans)
   */
  fontSans?: ('geist' | 'inter' | 'system') | null;
  /**
   * Serif font (--font-serif)
   */
  fontSerif?: ('merriweather' | 'lora' | 'system') | null;
  /**
   * Monospace font (--font-mono)
   */
  fontMono?: ('geist-mono' | 'jetbrains-mono') | null;
  /**
   * Base letter spacing, e.g. 0rem (--tracking-normal)
   */
  letterSpacing?: string | null;
  /**
   * Base border radius, e.g. 0.75rem (--radius)
   */
  radius?: string | null;
  /**
   * Base spacing unit, e.g. 0.25rem (--spacing)
   */
  spacing?: string | null;
  /**
   * Drives the --shadow-* scale.
   */
  shadow?: {
    color?: string | null;
    opacity?: number | null;
    blurRadius?: number | null;
    spread?: number | null;
    offsetX?: number | null;
    offsetY?: number | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-settings".
 */
export interface PricingSetting {
  id: number;
  heading?: string | null;
  showFreeTier?: boolean | null;
  subheading?: string | null;
  /**
   * Pick up to three paid plans to feature, in display order. Empty = all active plans by display order.
   */
  featuredPlans?: (number | Plan)[] | null;
  freeTier?: {
    name?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        url?: T;
        submenu?:
          | T
          | {
              label?: T;
              url?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  headerActions?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
        isButton?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  footerPolicies?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  social?:
    | T
    | {
        twitter?: T;
        github?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  appName?: T;
  brandLink?:
    | T
    | {
        url?: T;
        newTab?: T;
      };
  appIcon?: T;
  logoLight?: T;
  logoDark?: T;
  colorsLight?:
    | T
    | {
        background?: T;
        foreground?: T;
        card?: T;
        cardForeground?: T;
        popover?: T;
        popoverForeground?: T;
        primary?: T;
        primaryForeground?: T;
        secondary?: T;
        secondaryForeground?: T;
        muted?: T;
        mutedForeground?: T;
        accent?: T;
        accentForeground?: T;
        destructive?: T;
        destructiveForeground?: T;
        border?: T;
        input?: T;
        ring?: T;
        chart1?: T;
        chart2?: T;
        chart3?: T;
        chart4?: T;
        chart5?: T;
        sidebar?: T;
        sidebarForeground?: T;
        sidebarPrimary?: T;
        sidebarPrimaryForeground?: T;
        sidebarAccent?: T;
        sidebarAccentForeground?: T;
        sidebarBorder?: T;
        sidebarRing?: T;
        brand?: T;
        brandForeground?: T;
      };
  colorsDark?:
    | T
    | {
        background?: T;
        foreground?: T;
        card?: T;
        cardForeground?: T;
        popover?: T;
        popoverForeground?: T;
        primary?: T;
        primaryForeground?: T;
        secondary?: T;
        secondaryForeground?: T;
        muted?: T;
        mutedForeground?: T;
        accent?: T;
        accentForeground?: T;
        destructive?: T;
        destructiveForeground?: T;
        border?: T;
        input?: T;
        ring?: T;
        chart1?: T;
        chart2?: T;
        chart3?: T;
        chart4?: T;
        chart5?: T;
        sidebar?: T;
        sidebarForeground?: T;
        sidebarPrimary?: T;
        sidebarPrimaryForeground?: T;
        sidebarAccent?: T;
        sidebarAccentForeground?: T;
        sidebarBorder?: T;
        sidebarRing?: T;
        brand?: T;
        brandForeground?: T;
      };
  fontSans?: T;
  fontSerif?: T;
  fontMono?: T;
  letterSpacing?: T;
  radius?: T;
  spacing?: T;
  shadow?:
    | T
    | {
        color?: T;
        opacity?: T;
        blurRadius?: T;
        spread?: T;
        offsetX?: T;
        offsetY?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-settings_select".
 */
export interface PricingSettingsSelect<T extends boolean = true> {
  heading?: T;
  showFreeTier?: T;
  subheading?: T;
  featuredPlans?: T;
  freeTier?:
    | T
    | {
        name?: T;
        description?: T;
        ctaLabel?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
