/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    events: Event;
    videos: Video;
    audio: Audio;
    photos: Photo;
    locations: Location;
    pages: Page;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    audio: AudioSelect<false> | AudioSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    "site-settings": SiteSetting;
    "theme-settings": ThemeSetting;
  };
  globalsSelect: {
    "site-settings": SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    "theme-settings": ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  email?: string | null;
  name?: string | null;
  /**
   * Linked Supabase auth user id (managed by the SSO bridge).
   */
  supabaseUserId?: string | null;
  role: "admin" | "editor";
  updatedAt: string;
  createdAt: string;
  collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  tags?: string[] | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startsAt: string;
  endsAt?: string | null;
  location?: (number | null) | Location;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  slug: string;
  address?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  sourceType: "url" | "upload";
  url?: string | null;
  file?: (number | null) | Media;
  thumbnail?: (number | null) | Media;
  /**
   * Length in seconds.
   */
  duration?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio".
 */
export interface Audio {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  audioFile: number | Media;
  /**
   * Length in seconds.
   */
  duration?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  title: string;
  slug: string;
  image: number | Media;
  caption?: string | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "articles";
        value: number | Article;
      } | null)
    | ({
        relationTo: "events";
        value: number | Event;
      } | null)
    | ({
        relationTo: "videos";
        value: number | Video;
      } | null)
    | ({
        relationTo: "audio";
        value: number | Audio;
      } | null)
    | ({
        relationTo: "photos";
        value: number | Photo;
      } | null)
    | ({
        relationTo: "locations";
        value: number | Location;
      } | null)
    | ({
        relationTo: "pages";
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  supabaseUserId?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  author?: T;
  tags?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  sourceType?: T;
  url?: T;
  file?: T;
  thumbnail?: T;
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio_select".
 */
export interface AudioSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  audioFile?: T;
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  caption?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  header?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  social?: {
    twitter?: string | null;
    github?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Branding, colors, typography and styles for the entire app and this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  /**
   * Display name shown in the app shell and tab title.
   */
  appName?: string | null;
  /**
   * Square icon — used as the favicon (512×512 ideal).
   */
  appIcon?: (number | null) | Media;
  /**
   * Logo shown on light backgrounds.
   */
  logoLight?: (number | null) | Media;
  /**
   * Logo shown on dark backgrounds.
   */
  logoDark?: (number | null) | Media;
  colorsLight?: {
    /**
     * --background · any CSS color (oklch recommended)
     */
    background?: string | null;
    /**
     * --foreground · any CSS color (oklch recommended)
     */
    foreground?: string | null;
    /**
     * --card · any CSS color (oklch recommended)
     */
    card?: string | null;
    /**
     * --card-foreground · any CSS color (oklch recommended)
     */
    cardForeground?: string | null;
    /**
     * --popover · any CSS color (oklch recommended)
     */
    popover?: string | null;
    /**
     * --popover-foreground · any CSS color (oklch recommended)
     */
    popoverForeground?: string | null;
    /**
     * --primary · any CSS color (oklch recommended)
     */
    primary?: string | null;
    /**
     * --primary-foreground · any CSS color (oklch recommended)
     */
    primaryForeground?: string | null;
    /**
     * --secondary · any CSS color (oklch recommended)
     */
    secondary?: string | null;
    /**
     * --secondary-foreground · any CSS color (oklch recommended)
     */
    secondaryForeground?: string | null;
    /**
     * --muted · any CSS color (oklch recommended)
     */
    muted?: string | null;
    /**
     * --muted-foreground · any CSS color (oklch recommended)
     */
    mutedForeground?: string | null;
    /**
     * --accent · any CSS color (oklch recommended)
     */
    accent?: string | null;
    /**
     * --accent-foreground · any CSS color (oklch recommended)
     */
    accentForeground?: string | null;
    /**
     * --destructive · any CSS color (oklch recommended)
     */
    destructive?: string | null;
    /**
     * --destructive-foreground · any CSS color (oklch recommended)
     */
    destructiveForeground?: string | null;
    /**
     * --border · any CSS color (oklch recommended)
     */
    border?: string | null;
    /**
     * --input · any CSS color (oklch recommended)
     */
    input?: string | null;
    /**
     * --ring · any CSS color (oklch recommended)
     */
    ring?: string | null;
    /**
     * --chart-1 · any CSS color (oklch recommended)
     */
    chart1?: string | null;
    /**
     * --chart-2 · any CSS color (oklch recommended)
     */
    chart2?: string | null;
    /**
     * --chart-3 · any CSS color (oklch recommended)
     */
    chart3?: string | null;
    /**
     * --chart-4 · any CSS color (oklch recommended)
     */
    chart4?: string | null;
    /**
     * --chart-5 · any CSS color (oklch recommended)
     */
    chart5?: string | null;
    /**
     * --sidebar · any CSS color (oklch recommended)
     */
    sidebar?: string | null;
    /**
     * --sidebar-foreground · any CSS color (oklch recommended)
     */
    sidebarForeground?: string | null;
    /**
     * --sidebar-primary · any CSS color (oklch recommended)
     */
    sidebarPrimary?: string | null;
    /**
     * --sidebar-primary-foreground · any CSS color (oklch recommended)
     */
    sidebarPrimaryForeground?: string | null;
    /**
     * --sidebar-accent · any CSS color (oklch recommended)
     */
    sidebarAccent?: string | null;
    /**
     * --sidebar-accent-foreground · any CSS color (oklch recommended)
     */
    sidebarAccentForeground?: string | null;
    /**
     * --sidebar-border · any CSS color (oklch recommended)
     */
    sidebarBorder?: string | null;
    /**
     * --sidebar-ring · any CSS color (oklch recommended)
     */
    sidebarRing?: string | null;
  };
  colorsDark?: {
    /**
     * --background · any CSS color (oklch recommended)
     */
    background?: string | null;
    /**
     * --foreground · any CSS color (oklch recommended)
     */
    foreground?: string | null;
    /**
     * --card · any CSS color (oklch recommended)
     */
    card?: string | null;
    /**
     * --card-foreground · any CSS color (oklch recommended)
     */
    cardForeground?: string | null;
    /**
     * --popover · any CSS color (oklch recommended)
     */
    popover?: string | null;
    /**
     * --popover-foreground · any CSS color (oklch recommended)
     */
    popoverForeground?: string | null;
    /**
     * --primary · any CSS color (oklch recommended)
     */
    primary?: string | null;
    /**
     * --primary-foreground · any CSS color (oklch recommended)
     */
    primaryForeground?: string | null;
    /**
     * --secondary · any CSS color (oklch recommended)
     */
    secondary?: string | null;
    /**
     * --secondary-foreground · any CSS color (oklch recommended)
     */
    secondaryForeground?: string | null;
    /**
     * --muted · any CSS color (oklch recommended)
     */
    muted?: string | null;
    /**
     * --muted-foreground · any CSS color (oklch recommended)
     */
    mutedForeground?: string | null;
    /**
     * --accent · any CSS color (oklch recommended)
     */
    accent?: string | null;
    /**
     * --accent-foreground · any CSS color (oklch recommended)
     */
    accentForeground?: string | null;
    /**
     * --destructive · any CSS color (oklch recommended)
     */
    destructive?: string | null;
    /**
     * --destructive-foreground · any CSS color (oklch recommended)
     */
    destructiveForeground?: string | null;
    /**
     * --border · any CSS color (oklch recommended)
     */
    border?: string | null;
    /**
     * --input · any CSS color (oklch recommended)
     */
    input?: string | null;
    /**
     * --ring · any CSS color (oklch recommended)
     */
    ring?: string | null;
    /**
     * --chart-1 · any CSS color (oklch recommended)
     */
    chart1?: string | null;
    /**
     * --chart-2 · any CSS color (oklch recommended)
     */
    chart2?: string | null;
    /**
     * --chart-3 · any CSS color (oklch recommended)
     */
    chart3?: string | null;
    /**
     * --chart-4 · any CSS color (oklch recommended)
     */
    chart4?: string | null;
    /**
     * --chart-5 · any CSS color (oklch recommended)
     */
    chart5?: string | null;
    /**
     * --sidebar · any CSS color (oklch recommended)
     */
    sidebar?: string | null;
    /**
     * --sidebar-foreground · any CSS color (oklch recommended)
     */
    sidebarForeground?: string | null;
    /**
     * --sidebar-primary · any CSS color (oklch recommended)
     */
    sidebarPrimary?: string | null;
    /**
     * --sidebar-primary-foreground · any CSS color (oklch recommended)
     */
    sidebarPrimaryForeground?: string | null;
    /**
     * --sidebar-accent · any CSS color (oklch recommended)
     */
    sidebarAccent?: string | null;
    /**
     * --sidebar-accent-foreground · any CSS color (oklch recommended)
     */
    sidebarAccentForeground?: string | null;
    /**
     * --sidebar-border · any CSS color (oklch recommended)
     */
    sidebarBorder?: string | null;
    /**
     * --sidebar-ring · any CSS color (oklch recommended)
     */
    sidebarRing?: string | null;
  };
  /**
   * Body / UI font (--font-sans)
   */
  fontSans?: ("geist" | "inter" | "system") | null;
  /**
   * Serif font (--font-serif)
   */
  fontSerif?: ("merriweather" | "lora" | "system") | null;
  /**
   * Monospace font (--font-mono)
   */
  fontMono?: ("geist-mono" | "jetbrains-mono") | null;
  /**
   * Base letter spacing, e.g. 0rem (--tracking-normal)
   */
  letterSpacing?: string | null;
  /**
   * Base border radius, e.g. 0.75rem (--radius)
   */
  radius?: string | null;
  /**
   * Base spacing unit, e.g. 0.25rem (--spacing)
   */
  spacing?: string | null;
  /**
   * Drives the --shadow-* scale.
   */
  shadow?: {
    color?: string | null;
    opacity?: number | null;
    blurRadius?: number | null;
    spread?: number | null;
    offsetX?: number | null;
    offsetY?: number | null;
  };
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  social?:
    | T
    | {
        twitter?: T;
        github?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  appName?: T;
  appIcon?: T;
  logoLight?: T;
  logoDark?: T;
  colorsLight?:
    | T
    | {
        background?: T;
        foreground?: T;
        card?: T;
        cardForeground?: T;
        popover?: T;
        popoverForeground?: T;
        primary?: T;
        primaryForeground?: T;
        secondary?: T;
        secondaryForeground?: T;
        muted?: T;
        mutedForeground?: T;
        accent?: T;
        accentForeground?: T;
        destructive?: T;
        destructiveForeground?: T;
        border?: T;
        input?: T;
        ring?: T;
        chart1?: T;
        chart2?: T;
        chart3?: T;
        chart4?: T;
        chart5?: T;
        sidebar?: T;
        sidebarForeground?: T;
        sidebarPrimary?: T;
        sidebarPrimaryForeground?: T;
        sidebarAccent?: T;
        sidebarAccentForeground?: T;
        sidebarBorder?: T;
        sidebarRing?: T;
      };
  colorsDark?:
    | T
    | {
        background?: T;
        foreground?: T;
        card?: T;
        cardForeground?: T;
        popover?: T;
        popoverForeground?: T;
        primary?: T;
        primaryForeground?: T;
        secondary?: T;
        secondaryForeground?: T;
        muted?: T;
        mutedForeground?: T;
        accent?: T;
        accentForeground?: T;
        destructive?: T;
        destructiveForeground?: T;
        border?: T;
        input?: T;
        ring?: T;
        chart1?: T;
        chart2?: T;
        chart3?: T;
        chart4?: T;
        chart5?: T;
        sidebar?: T;
        sidebarForeground?: T;
        sidebarPrimary?: T;
        sidebarPrimaryForeground?: T;
        sidebarAccent?: T;
        sidebarAccentForeground?: T;
        sidebarBorder?: T;
        sidebarRing?: T;
      };
  fontSans?: T;
  fontSerif?: T;
  fontMono?: T;
  letterSpacing?: T;
  radius?: T;
  spacing?: T;
  shadow?:
    | T
    | {
        color?: T;
        opacity?: T;
        blurRadius?: T;
        spread?: T;
        offsetX?: T;
        offsetY?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
