import { createEnv } from "@t3-oss/env-nextjs";
import { vercel } from "@t3-oss/env-nextjs/presets-zod";
import { z } from "zod/v4";

import {
  extClientEnv,
  extClientRuntimeEnv,
  extServerEnv,
} from "./ext/env.generated";

/**
 * Build-time placeholders for the public Supabase env. A one-click / v0 deploy
 * builds with no env set, so these get baked into the client bundle and the
 * deployed app can't reach Supabase until the real values are set AND the app
 * is redeployed. `isSupabaseConfigured()` (see `~/lib/supabase/config`) detects
 * this so the UI can warn instead of failing with a cryptic "Failed to fetch".
 * Keyed off the anon-key sentinel because the URL placeholder doubles as the
 * real local-dev URL, so it can't tell "unconfigured" apart from "local dev".
 */
export const SUPABASE_URL_PLACEHOLDER = "http://127.0.0.1:54321";
export const SUPABASE_ANON_KEY_PLACEHOLDER = "set-in-vercel-env";

/**
 * Web app environment. Server vars are secrets (never bundled to the client);
 * client vars MUST be `NEXT_PUBLIC_`-prefixed. The shared, platform-agnostic
 * schema lives in `@acme/config` (used by edge functions); this file is the
 * Next-specific, build-time-validated view of it.
 */
export const env = createEnv({
  extends: [vercel()],
  shared: {
    NODE_ENV: z
      .enum(["development", "production", "test"])
      .default("development"),
  },
  /** Server-only — secrets. Never exposed to the browser. */
  server: {
    // Optional so the kit boots without it, but needed by the staff-invite
    // hook (payload/hooks/invite-user.ts → lib/supabase/admin.ts): inviting a
    // user from /admin fails with a clear error until it's set. Supabase edge
    // functions receive the service role from Supabase's injected env.
    SUPABASE_SERVICE_ROLE_KEY: z.string().min(1).optional(),
    SUPABASE_DB_URL: z.url().optional(),
    // Postgres URLs auto-injected by the Vercel<->Supabase integration. The
    // runtime DB bootstrap (lib/db/bootstrap.ts → resolveAdminDbUrl) uses them
    // when SUPABASE_DB_URL isn't set, so a fresh hosted project self-provisions
    // on first boot with zero manual env. It prefers the IPv4 SESSION pooler it
    // derives from POSTGRES_URL (the transaction pooler, port 6543 → 5432) over
    // POSTGRES_URL_NON_POOLING: the latter is Supabase's DIRECT connection,
    // which is IPv6-only without the IPv4 add-on and so unreachable from Vercel.
    POSTGRES_URL: z.string().min(1).optional(),
    POSTGRES_URL_NON_POOLING: z.string().min(1).optional(),
    // Opt-out for the runtime DB bootstrap (e.g. when CI owns migrations).
    DB_BOOTSTRAP: z.enum(["on", "off"]).optional(),
    AI_GATEWAY_API_KEY: z.string().min(1).optional(),
    STRIPE_SECRET_KEY: z.string().min(1).optional(),
    STRIPE_WEBHOOK_SECRET: z.string().min(1).optional(),
    // Signing secret for the PAYLOAD Stripe webhook endpoint
    // (/cms-api/stripe/webhooks, via @payloadcms/plugin-stripe) — a separate
    // Stripe endpoint from the Supabase edge function's STRIPE_WEBHOOK_SECRET.
    STRIPE_WEBHOOKS_ENDPOINT_SECRET: z.string().min(1).optional(),
    STRIPE_PRICE_MONTHLY: z.string().min(1).optional(),
    STRIPE_PRICE_YEARLY: z.string().min(1).optional(),
    // Payload CMS (server-only). Payload reads these directly from process.env
    // (incl. the `payload` CLI), so they're optional here; declared for typing
    // and to keep .env validated. See .env.example.
    PAYLOAD_DATABASE_URL: z.string().min(1).optional(),
    PAYLOAD_SECRET: z.string().min(1).optional(),
    PAYLOAD_PREVIEW_SECRET: z.string().min(1).optional(),
    S3_ENDPOINT: z.url().optional(),
    S3_REGION: z.string().min(1).optional(),
    S3_ACCESS_KEY_ID: z.string().min(1).optional(),
    S3_SECRET_ACCESS_KEY: z.string().min(1).optional(),
    S3_BUCKET: z.string().min(1).optional(),
    // Extension framework admin ops (docs/EXTENSIONS-PLAN.md §6). Without
    // GITHUB_OPS_TOKEN the /admin/extensions page is read-only (it shows
    // copy-paste CLI instructions instead of dispatching workflows).
    GITHUB_OPS_TOKEN: z.string().min(1).optional(),
    // owner/repo; defaults from the Vercel-injected repo metadata below.
    GITHUB_REPO: z
      .string()
      .regex(/^[^/]+\/[^/]+$/)
      .optional(),
    VERCEL_GIT_REPO_OWNER: z.string().min(1).optional(),
    VERCEL_GIT_REPO_SLUG: z.string().min(1).optional(),
    EXT_CATALOG_URL: z.url().optional(),
    // Server env declared by installed extensions (EXT_*) — generated by
    // `pnpm ext sync` from each extension's ./env shape.
    ...extServerEnv,
  },
  /** Client-safe — compiled into the browser bundle (publishable/anon only). */
  client: {
    // Build-time placeholders so a one-click / v0 deploy builds with no env set.
    // They're baked into the bundle, so the deployed app is non-functional until
    // you set the real values (e.g. the Vercel Supabase integration) AND redeploy.
    // Locally, set them in `.env` (see .env.example). The URL must stay a valid URL.
    NEXT_PUBLIC_SUPABASE_URL: z.url().default(SUPABASE_URL_PLACEHOLDER),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z
      .string()
      .min(1)
      .default(SUPABASE_ANON_KEY_PLACEHOLDER),
    // Supabase's new API-key system renamed the browser key "anon" →
    // "publishable", and the Vercel<->Supabase integration now injects it under
    // this name. Optional fallback for NEXT_PUBLIC_SUPABASE_ANON_KEY (resolved
    // by `supabaseAnonKey()` below) — supabase-js accepts either. So a fresh
    // clone-and-connect deploy gets a working browser client with no manual env.
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: z.string().min(1).optional(),
    // Local/dev default origin. On Vercel this is superseded by the auto-injected
    // production URL below (see ~/lib/site-url for the resolution order), so a
    // default deploy targets the real domain without any manual env.
    NEXT_PUBLIC_APP_URL: z.url().default("http://localhost:3000"),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().optional(),
    // Origin hosting the Payload REST API. In the browser the app reads content
    // same-origin (relative /cms-api); this is mainly for completeness/SSR.
    NEXT_PUBLIC_CMS_URL: z.url().optional(),
    // Explicit public-origin override — set to your custom domain to pin every
    // auth/Stripe/OG redirect to it (e.g. https://app.example.com).
    NEXT_PUBLIC_SITE_URL: z.url().optional(),
    // Auto-injected by Vercel for Next.js (no scheme, e.g. `my-app.vercel.app`).
    // PROJECT_PRODUCTION_URL is the stable production domain; VERCEL_URL is the
    // per-deployment URL. Both optional so local/non-Vercel builds still pass.
    NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL: z.string().min(1).optional(),
    NEXT_PUBLIC_VERCEL_URL: z.string().min(1).optional(),
    // Client env declared by installed extensions (NEXT_PUBLIC_EXT_*).
    ...extClientEnv,
  },
  /**
   * Destructure from process.env so vars aren't tree-shaken away.
   */
  experimental__runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CMS_URL: process.env.NEXT_PUBLIC_CMS_URL,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL:
      process.env.NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL,
    NEXT_PUBLIC_VERCEL_URL: process.env.NEXT_PUBLIC_VERCEL_URL,
    ...extClientRuntimeEnv,
  },
  // Do NOT skip on `process.env.CI`. Vercel sets CI=1 during builds, and when
  // validation is skipped `@t3-oss/env-nextjs` returns raw `process.env`
  // *without* applying the `.default()`s above — so `NEXT_PUBLIC_APP_URL` became
  // `undefined` and `next build` crashed on `new URL(undefined)` for a one-click
  // deploy with no env set. Letting validation run is what makes the documented
  // build-time placeholders actually take effect (and still fails loudly on a
  // genuinely malformed value). We only skip for `lint`, where eslint loads
  // `next.config.js` (which imports this file) but no real env is available.
  skipValidation: process.env.npm_lifecycle_event === "lint",
});

/**
 * The browser/anon Supabase key, resolving the new API-key naming. The
 * Vercel<->Supabase integration now injects it as
 * NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ("anon" → "publishable" in Supabase's new
 * key system); local dev and older setups use NEXT_PUBLIC_SUPABASE_ANON_KEY.
 * supabase-js accepts either. Returns the build placeholder only when neither is
 * set (a bare one-click deploy), which `isSupabaseConfigured()` detects.
 */
export function supabaseAnonKey(): string {
  if (env.NEXT_PUBLIC_SUPABASE_ANON_KEY !== SUPABASE_ANON_KEY_PLACEHOLDER) {
    return env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  }
  return (
    env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ??
    env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  );
}
