import * as migration_20260613_023123_ext_docs_initial from "./20260613_023123_ext_docs_initial";

/**
 * Payload (cms-schema) migrations for ext-docs — generated by
 * `pnpm ext payload-migrate docs <desc>` and relocated here. Never hand-edit.
 */
export const migrations = [
  {
    up: migration_20260613_023123_ext_docs_initial.up,
    down: migration_20260613_023123_ext_docs_initial.down,
    name: "20260613_023123_ext_docs_initial",
  },
];
