/* eslint-disable */
// GENERATED by `pnpm ext sync` — DO NOT EDIT.
// Recomputed from extensions/*/extension.config.ts; a stale copy fails
// `pnpm test` via apps/nextjs/src/ext/registry-drift.test.ts.
export { RemindersScreen as default } from "@acme/ext-reminders/native";
