import type { LoadedExtension } from "./manifests";
import { EXT_PATHS } from "./paths";

/**
 * Pure, deterministic builders for every generated file (registries, env
 * modules, route stubs, transpile list). Inputs are the loaded extensions
 * (already sorted by slug); same inputs always produce byte-identical output —
 * the drift test (apps/nextjs/src/ext/registry-drift.test.ts) recomputes these
 * and compares against the committed files.
 *
 * No timestamps, no environment reads, no formatting passes: output is final.
 */

export interface GeneratedFile {
  /** Repo-relative posix path. */
  path: string;
  content: string;
  /** Owning extension — set for route stubs (sync records them in the lock). */
  slug?: string;
}

const HEADER = `// GENERATED by \`pnpm ext sync\` — DO NOT EDIT.
// Recomputed from extensions/*/extension.config.ts; a stale copy fails
// \`pnpm test\` via apps/nextjs/src/ext/registry-drift.test.ts.
`;

const ESLINT_OFF = "/* eslint-disable */\n";

const ident = (slug: string): string => slug.replace(/-/g, "_");

const sysExt = (m: LoadedExtension["manifest"]): boolean =>
  m.routes.web.some((r) => r.mount !== undefined) ||
  m.routes.native.some((r) => r.mount !== undefined);

const quote = (s: string): string => JSON.stringify(s);

interface NavLiteral {
  key: string;
  extension: string;
  title: string;
  href: string;
  icon?: string;
  order: number;
}

function navLiterals(
  exts: LoadedExtension[],
  platform: "web" | "native",
): NavLiteral[] {
  const out: NavLiteral[] = [];
  for (const { manifest: m } of exts) {
    if (!m.platforms[platform]) continue;
    m.nav[platform].forEach((entry, i) => {
      out.push({
        key: `ext:${m.slug}:${i}`,
        extension: m.slug,
        title: entry.title,
        href: entry.href,
        icon: entry.icon,
        order: entry.order,
      });
    });
  }
  return out;
}

function renderNav(items: NavLiteral[], indent: string): string {
  if (items.length === 0) return "[]";
  const rows = items.map(
    (n) =>
      `${indent}  { key: ${quote(n.key)}, extension: ${quote(n.extension)}, title: ${quote(n.title)}, href: ${quote(n.href)}, ${n.icon ? `icon: ${quote(n.icon)}, ` : ""}order: ${n.order} },`,
  );
  return `[\n${rows.join("\n")}\n${indent}]`;
}

function renderInstalled(exts: LoadedExtension[]): string {
  if (exts.length === 0) return "[]";
  const rows = exts.map(
    ({ manifest: m }) =>
      `  { slug: ${quote(m.slug)}, name: ${quote(m.name)}, version: ${quote(m.version)}, system: ${sysExt(m)} },`,
  );
  return `[\n${rows.join("\n")}\n]`;
}

const SHARED_TYPES = `export interface ExtInstalled {
  slug: string;
  name: string;
  version: string;
  /** True when the app shell depends on this extension's mounts (e.g. the home screen). */
  system: boolean;
}

export interface ExtNavDefault {
  key: string;
  extension: string;
  title: string;
  href: string;
  icon?: string;
  order: number;
}
`;

/** apps/nextjs/src/ext/registry.client.generated.ts */
export function buildNextClientRegistry(exts: LoadedExtension[]): string {
  const webExts = exts.filter((e) => e.manifest.platforms.web);
  const widgetExts = webExts.filter((e) => e.manifest.widgets.web);
  const iconNames = [
    ...new Set(
      webExts.flatMap((e) =>
        e.manifest.nav.web.flatMap((n) => (n.icon ? [n.icon] : [])),
      ),
    ),
  ].sort();

  const imports: string[] = ['import type * as React from "react";'];
  if (iconNames.length > 0) {
    imports.push(
      `import { ${iconNames.join(", ")} } from "@tabler/icons-react";`,
    );
  }
  for (const e of widgetExts) {
    imports.push(
      `import { ${e.manifest.widgets.web} as widget_${ident(e.manifest.slug)} } from "${e.packageName}/web";`,
    );
  }

  const widgets =
    widgetExts.length === 0
      ? "[]"
      : `[\n${widgetExts
          .map(
            (e) =>
              `  { slug: ${quote(e.manifest.slug)}, Widget: widget_${ident(e.manifest.slug)} },`,
          )
          .join("\n")}\n]`;

  const icons =
    iconNames.length === 0
      ? "{}"
      : `{\n${iconNames.map((n) => `  ${n}: ${n},`).join("\n")}\n}`;

  return `${ESLINT_OFF}${HEADER}${imports.join("\n")}

${SHARED_TYPES}
/** Every installed extension (from the vendored manifests). */
export const extInstalled: ExtInstalled[] = ${renderInstalled(exts)};

/**
 * Manifest nav DEFAULTS — seeded into the CMS-driven menu by the boot
 * reconcile (lib/ext/reconcile-nav.ts), never rendered directly.
 */
export const extNavDefaults: { web: ExtNavDefault[]; native: ExtNavDefault[] } = {
  web: ${renderNav(navLiterals(exts, "web"), "  ")},
  native: ${renderNav(navLiterals(exts, "native"), "  ")},
};

/** Dashboard widgets declared by installed extensions (web components). */
export const extWidgets: { slug: string; Widget: React.ComponentType }[] = ${widgets};

/** Icon names referenced by extension nav defaults → components. */
export const extIcons: Record<string, React.ComponentType<{ className?: string }>> = ${icons};

export function hasExtension(slug: string): boolean {
  return extInstalled.some((e) => e.slug === slug);
}
`;
}

/** apps/nextjs/src/ext/registry.server.generated.ts */
export function buildNextServerRegistry(exts: LoadedExtension[]): string {
  const serverExts = exts.filter((e) => e.manifest.server.routes);
  const publicExts = exts.filter((e) => e.manifest.server.publicRoutes);
  const imports: string[] = [];
  for (const e of exts) {
    const names = [
      ...(e.manifest.server.routes
        ? [`routes as routes_${ident(e.manifest.slug)}`]
        : []),
      ...(e.manifest.server.publicRoutes
        ? [`publicRoutes as publicRoutes_${ident(e.manifest.slug)}`]
        : []),
    ];
    if (names.length > 0) {
      imports.push(
        `import { ${names.join(", ")} } from "${e.packageName}/server";`,
      );
    }
  }
  const table = (rows: LoadedExtension[], prefix: string): string =>
    rows.length === 0
      ? "{}"
      : `{\n${rows
          .map(
            (e) =>
              `  ${quote(e.manifest.slug)}: ${prefix}_${ident(e.manifest.slug)},`,
          )
          .join("\n")}\n}`;

  return `${ESLINT_OFF}${HEADER}import "server-only";

import type { ExtPublicRouteTable, ExtRouteTable } from "@acme/ext-kit/server";
${imports.length > 0 ? `\n${imports.join("\n")}\n` : ""}
/** slug → authed route table, dispatched by /api/ext/[ext]/[[...route]]. */
export const extServerRoutes: Record<string, ExtRouteTable> = ${table(serverExts, "routes")};

/** slug → PUBLIC route table (no session required; still rate-limited). */
export const extPublicRoutes: Record<string, ExtPublicRouteTable> = ${table(publicExts, "publicRoutes")};
`;
}

/** apps/nextjs/src/ext/registry.payload.generated.ts */
export function buildNextPayloadRegistry(exts: LoadedExtension[]): string {
  const cmsExts = exts.filter((e) => {
    const c = e.manifest.cms;
    return (
      c.collections.length > 0 ||
      c.globals.length > 0 ||
      c.hasPlugins ||
      c.hasMigrations ||
      c.hasSeed ||
      c.hasSettings
    );
  });

  const imports = cmsExts.map(
    (e) =>
      `import * as payload_${ident(e.manifest.slug)} from "${e.packageName}/payload";`,
  );

  const spread = (cond: boolean, expr: string): string[] =>
    cond ? [expr] : [];

  const collections = cmsExts.flatMap((e) =>
    spread(
      e.manifest.cms.collections.length > 0,
      `  ...payload_${ident(e.manifest.slug)}.collections,`,
    ),
  );
  const globals = cmsExts.flatMap((e) => [
    ...spread(
      e.manifest.cms.globals.length > 0,
      `  ...payload_${ident(e.manifest.slug)}.globals,`,
    ),
    ...spread(
      e.manifest.cms.hasSettings,
      `  payload_${ident(e.manifest.slug)}.settings.global,`,
    ),
  ]);
  const plugins = cmsExts.flatMap((e) =>
    spread(
      e.manifest.cms.hasPlugins,
      `  ...payload_${ident(e.manifest.slug)}.plugins,`,
    ),
  );
  const migrations = cmsExts.flatMap((e) =>
    spread(
      e.manifest.cms.hasMigrations,
      `  ...payload_${ident(e.manifest.slug)}.migrations,`,
    ),
  );
  const seeds = cmsExts.flatMap((e) =>
    spread(
      e.manifest.cms.hasSeed,
      `  ...payload_${ident(e.manifest.slug)}.seed,`,
    ),
  );
  const settings = cmsExts.flatMap((e) =>
    spread(
      e.manifest.cms.hasSettings,
      `  ${quote(e.manifest.slug)}: payload_${ident(e.manifest.slug)}.settings,`,
    ),
  );

  const arr = (rows: string[]): string =>
    rows.length === 0 ? "[]" : `[\n${rows.join("\n")}\n]`;
  const obj = (rows: string[]): string =>
    rows.length === 0 ? "{}" : `{\n${rows.join("\n")}\n}`;

  return `${ESLINT_OFF}${HEADER}import type { CollectionConfig, Config, GlobalConfig } from "payload";

import type { ExtensionSettings, ExtSeedStep } from "@acme/ext-kit/payload";
${imports.length > 0 ? `\n${imports.join("\n")}\n` : ""}
export interface ExtPayloadMigration {
  name: string;
  up: (args: any) => Promise<void>;
  down: (args: any) => Promise<void>;
}

export const extCollections: CollectionConfig[] = ${arr(collections)};

export const extGlobals: GlobalConfig[] = ${arr(globals)};

export const extPlugins: NonNullable<Config["plugins"]> = ${arr(plugins)};

export const extPayloadMigrations: ExtPayloadMigration[] = ${arr(migrations)};

export const extSeedSteps: ExtSeedStep[] = ${arr(seeds)};

/** slug → settings definition (admin settings screens, §1.7). */
export const extSettings: Record<string, ExtensionSettings> = ${obj(settings)};
`;
}

/** apps/nextjs/src/ext/env.generated.ts */
export function buildNextEnv(exts: LoadedExtension[]): string {
  const envExts = exts.filter(
    (e) => e.manifest.env.hasServer || e.manifest.env.hasClient,
  );
  const imports = envExts.map(
    (e) =>
      `import extEnv_${ident(e.manifest.slug)} from "${e.packageName}/env";`,
  );

  const serverSpreads = envExts
    .filter((e) => e.manifest.env.hasServer)
    .map((e) => `  ...extEnv_${ident(e.manifest.slug)}.server,`);

  const clientRows: string[] = [];
  const runtimeRows: string[] = [];
  for (const e of envExts) {
    if (!e.manifest.env.hasClient) continue;
    for (const key of e.envClientKeys) {
      clientRows.push(
        `  NEXT_PUBLIC_${key}: extEnv_${ident(e.manifest.slug)}.client.${key},`,
      );
      runtimeRows.push(`  NEXT_PUBLIC_${key}: process.env.NEXT_PUBLIC_${key},`);
    }
  }

  const obj = (rows: string[]): string =>
    rows.length === 0 ? "{}" : `{\n${rows.join("\n")}\n}`;

  return `${ESLINT_OFF}${HEADER}${imports.length > 0 ? `${imports.join("\n")}\n\n` : ""}/** Merged server-only env shapes from installed extensions (EXT_*). */
export const extServerEnv = ${obj(serverSpreads)};

/** Merged client env shapes (NEXT_PUBLIC_EXT_*). */
export const extClientEnv = ${obj(clientRows)};

/** Literal process.env reads (t3-env requires them for client vars). */
export const extClientRuntimeEnv = ${obj(runtimeRows)};
`;
}

/** apps/expo/src/ext/registry.generated.ts */
export function buildExpoRegistry(exts: LoadedExtension[]): string {
  const nativeExts = exts.filter((e) => e.manifest.platforms.native);
  const widgetExts = nativeExts.filter((e) => e.manifest.widgets.native);

  const imports: string[] = ['import type * as React from "react";'];
  // Side-effect imports: each native extension's ./native entry loads at app
  // start (the root _layout imports this registry), so extensions can register
  // native handlers on boot — e.g. notifications' setNotificationHandler.
  for (const e of nativeExts) {
    if (e.manifest.widgets.native) continue; // imported by name below
    if (e.manifest.routes.native.length === 0) continue; // no native entry
    imports.push(`import "${e.packageName}/native";`);
  }
  for (const e of widgetExts) {
    imports.push(
      `import { ${e.manifest.widgets.native} as widget_${ident(e.manifest.slug)} } from "${e.packageName}/native";`,
    );
  }

  const widgets =
    widgetExts.length === 0
      ? "[]"
      : `[\n${widgetExts
          .map(
            (e) =>
              `  { slug: ${quote(e.manifest.slug)}, Widget: widget_${ident(e.manifest.slug)} },`,
          )
          .join("\n")}\n]`;

  return `${ESLINT_OFF}${HEADER}${imports.join("\n")}

${SHARED_TYPES}
export const extInstalled: ExtInstalled[] = ${renderInstalled(exts)};

/** Native nav defaults — fallback for useNavMenu() while offline/loading. */
export const extNavDefaults: { native: ExtNavDefault[] } = {
  native: ${renderNav(navLiterals(exts, "native"), "  ")},
};

/** Home-screen widgets declared by installed extensions (native components). */
export const extWidgets: { slug: string; Widget: React.ComponentType }[] = ${widgets};

export function hasExtension(slug: string): boolean {
  return extInstalled.some((e) => e.slug === slug);
}
`;
}

/** apps/expo/src/ext/env.generated.ts */
export function buildExpoEnv(exts: LoadedExtension[]): string {
  const envExts = exts.filter(
    (e) => e.manifest.env.hasClient && e.manifest.platforms.native,
  );
  if (envExts.length === 0) {
    return `${ESLINT_OFF}${HEADER}/** Extension client env (EXPO_PUBLIC_EXT_*) — none installed declare any. */
export const extEnv = {};
`;
  }

  const imports = envExts.map(
    (e) =>
      `import extEnv_${ident(e.manifest.slug)} from "${e.packageName}/env";`,
  );
  const shapeRows: string[] = [];
  const readRows: string[] = [];
  for (const e of envExts) {
    for (const key of e.envClientKeys) {
      shapeRows.push(
        `  EXPO_PUBLIC_${key}: extEnv_${ident(e.manifest.slug)}.client.${key},`,
      );
      readRows.push(`  EXPO_PUBLIC_${key}: process.env.EXPO_PUBLIC_${key},`);
    }
  }

  return `${ESLINT_OFF}${HEADER}import { z } from "zod/v4";

${imports.join("\n")}

/** Extension client env (EXPO_PUBLIC_* is inlined at build time — literal reads only). */
export const extEnv = z
  .object({
${shapeRows.join("\n")}
  })
  .parse({
${readRows.join("\n")}
  });
`;
}

/** apps/nextjs/ext-packages.generated.json (transpilePackages additions). */
export function buildTranspileJson(exts: LoadedExtension[]): string {
  return `${JSON.stringify(
    exts.map((e) => e.packageName),
    null,
    2,
  )}\n`;
}

/** Generated route stubs for both apps (machine-owned subtrees). */
export function buildStubs(exts: LoadedExtension[]): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const e of exts) {
    const m = e.manifest;
    const slug = m.slug;

    if (m.platforms.web) {
      // One enabled-gating layout per distinct (group, mount base).
      const bases = new Set<string>();
      for (const r of m.routes.web) {
        const group =
          r.area === "public"
            ? EXT_PATHS.nextPublicGroup
            : EXT_PATHS.nextAppGroup;
        const base = r.mount ? r.mount.replace(/^\//, "") : `x/${slug}`;
        bases.add(`${group}/${base}`);
        const seg = r.path ? `/${r.path}` : "";
        files.push({
          path: `${group}/${base}${seg}/page.tsx`,
          slug,
          content: `${ESLINT_OFF}${HEADER}export { ${r.component} as default } from "${e.packageName}/web";\n`,
        });
      }
      for (const baseDir of [...bases].sort()) {
        files.push({
          path: `${baseDir}/layout.tsx`,
          slug,
          content: `${ESLINT_OFF}${HEADER}import type { ReactNode } from "react";
import { notFound } from "next/navigation";

import { isExtensionEnabled } from "~/lib/ext/enabled";

/** Runtime enable/disable gate — disabling the extension 404s its pages. */
export default async function ExtensionLayout({
  children,
}: {
  children: ReactNode;
}) {
  if (!(await isExtensionEnabled(${quote(slug)}))) notFound();
  return children;
}
`,
        });
      }
    }

    if (m.platforms.native) {
      for (const r of m.routes.native) {
        // Native gating is nav-level (disabled extensions disappear from the
        // menu and their APIs 404); Expo Router has no server gate to add.
        const file =
          r.mount === "index"
            ? "index"
            : `x/${slug}/${r.path === "" ? "index" : r.path}`;
        files.push({
          path: `${EXT_PATHS.expoAppGroup}/${file}.tsx`,
          slug,
          content: `${ESLINT_OFF}${HEADER}export { ${r.component} as default } from "${e.packageName}/native";\n`,
        });
      }
    }
  }

  return files.sort((a, b) => a.path.localeCompare(b.path));
}

/**
 * Copies of extension Payload migrations, materialized into the host
 * migrationDir so the local `payload migrate` CLI (db:reset) applies them —
 * otherwise dev push has to reconcile renamed cms tables interactively.
 * Production applies the same names via prodMigrations; the ledger dedupes.
 */
export function buildPayloadMigrationCopies(
  exts: LoadedExtension[],
): GeneratedFile[] {
  return exts.flatMap((e) =>
    e.payloadMigrations.map((m) => ({
      path: `apps/nextjs/src/payload/migrations/${m.name}.ts`,
      slug: e.manifest.slug,
      content: `// GENERATED copy (\`pnpm ext sync\`) of extensions/${e.manifest.slug}/src/payload/migrations/${m.name}.ts\n// so the local \`payload migrate\` CLI applies it — do not edit.\n${m.content}`,
    })),
  );
}

/** Everything the drift test compares (registries + env + stubs + transpile list). */
export function buildAllGeneratedFiles(
  exts: LoadedExtension[],
): GeneratedFile[] {
  return [
    {
      path: EXT_PATHS.nextClientRegistry,
      content: buildNextClientRegistry(exts),
    },
    {
      path: EXT_PATHS.nextServerRegistry,
      content: buildNextServerRegistry(exts),
    },
    {
      path: EXT_PATHS.nextPayloadRegistry,
      content: buildNextPayloadRegistry(exts),
    },
    { path: EXT_PATHS.nextEnv, content: buildNextEnv(exts) },
    { path: EXT_PATHS.nextTranspileJson, content: buildTranspileJson(exts) },
    { path: EXT_PATHS.expoRegistry, content: buildExpoRegistry(exts) },
    { path: EXT_PATHS.expoEnv, content: buildExpoEnv(exts) },
    ...buildStubs(exts),
    ...buildPayloadMigrationCopies(exts),
  ];
}

const ENV_FENCE_START = "# --- extensions (generated) ---";
const ENV_FENCE_END = "# --- end extensions (generated) ---";

/** The fenced .env.example block listing extension env vars. */
export function buildEnvExampleBlock(exts: LoadedExtension[]): string {
  const lines: string[] = [
    ENV_FENCE_START,
    "# Managed by `pnpm ext sync` — do not edit between these markers.",
    '# Uncomment + set per extension; unset optional vars must stay ABSENT (not "").',
  ];
  for (const e of exts) {
    if (e.envServerKeys.length === 0 && e.envClientKeys.length === 0) continue;
    lines.push("", `# ${e.manifest.name} (${e.manifest.slug})`);
    for (const key of e.envServerKeys) lines.push(`# ${key}=`);
    for (const key of e.envClientKeys) {
      lines.push(`# NEXT_PUBLIC_${key}=`, `# EXPO_PUBLIC_${key}=`);
    }
  }
  lines.push(ENV_FENCE_END);
  return lines.join("\n");
}

/** Replace (or append) the fenced block inside the .env.example content. */
export function applyEnvExampleBlock(current: string, block: string): string {
  const start = current.indexOf(ENV_FENCE_START);
  const end = current.indexOf(ENV_FENCE_END);
  if (start !== -1 && end !== -1 && end > start) {
    return `${current.slice(0, start)}${block}${current.slice(end + ENV_FENCE_END.length)}`;
  }
  const sep = current.endsWith("\n") ? "\n" : "\n\n";
  return `${current}${sep}${block}\n`;
}
