import { defineConfig } from "eslint/config";

import { baseConfig } from "@acme/eslint-config/base";
import { reactConfig } from "@acme/eslint-config/react";

export default defineConfig(
  {
    // payload/migrations/** is generated by `payload migrate:create`
    // (relocated here by the payload-migrate flow) and ships verbatim.
    ignores: ["supabase/**", "src/payload/migrations/2*"],
  },
  baseConfig,
  reactConfig,
);
